name: Publish And Deploy 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: ca-solution
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '7.x'
  API_PATH: './CASolution.Api'
  INFRASTRUCTURE_PATH: './CASolution.Infrastructure'
  SLN_PATH: './CASolution.sln'

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ${{ env.SLN_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SLN_PATH }} -c Release --no-restore
        
      - name: Publish
        run: dotnet publish ${{ env.API_PATH }} -c Release --no-build -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Install EF Tool
        run : dotnet tool install -g dotnet-ef

      - name : Boundle Migration
        run : dotnet ef migrations bundle --runtime linux-x64 -p ${{ env.INFRASTRUCTURE_PATH }} -s ${{ env.API_PATH }} -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/migrate 

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
